export type SkillCategory =
    | 'FRONTEND'
    | 'BACKEND'
    | 'FULLSTACK'
    | 'MOBILE'
    | 'DEVOPS'
    | 'CLOUD'
    | 'DATA'
    | 'AI_ML'
    | 'SECURITY'
    | 'DATABASE'
    | 'TESTING'
    | 'PROJECT_MANAGEMENT'
    | 'DESIGN'
    | 'OTHER'